# Generated by Django 2.2.2 on 2019-06-11 04:42

from django.db import migrations, models
import django.db.models.deletion

def initial_report_types(apps, schema_editor):
    ReportType = apps.get_model('journal', 'ReportType')
    ReportType.objects.create(title='Info')
    ReportType.objects.create(title='Warning')
    ReportType.objects.create(title='Failure')
    ReportType.objects.create(title='Success')


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('watchdog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('author', models.TextField(max_length=50)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('watchdog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='watchdog.Service')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='journal.ReportType')),
            ],
        ),
        migrations.RunPython(initial_report_types)
    ]
