# Generated by Django 2.2.2 on 2019-06-11 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('check_url', models.CharField(max_length=255)),
                ('last_failed', models.DateTimeField(null=True)),
                ('recovered', models.DateTimeField(null=True)),
                ('failure', models.BooleanField(default=False)),
                ('prechecked', models.BooleanField(default=False)),
                ('precheck_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('enable_prechecking', models.BooleanField(default=True)),
                ('enable_automatic_reports', models.BooleanField(default=True)),
                ('downtime', models.IntegerField(default=0)),
                ('last_downtime_updated', models.DateTimeField(auto_now_add=True, null=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
